# Generated by Django 4.2.2 on 2023-06-06 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('none', 'None'), ('redovni', 'Redovni'), ('izvanredni', 'Izvanredni')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=255)),
                ('kod', models.CharField(max_length=16)),
                ('program', models.TextField()),
                ('bodovi', models.IntegerField()),
                ('sem_redovni', models.IntegerField()),
                ('sem_izvanredni', models.IntegerField()),
                ('izborni', models.CharField(choices=[('da', 'Da'), ('ne', 'Ne')], max_length=2)),
                ('nositelj', models.ForeignKey(limit_choices_to={'uloga__ime': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, to='app1.korisnik')),
            ],
        ),
        migrations.CreateModel(
            name='Uloga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Upis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.predmet')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.korisnik')),
            ],
        ),
        migrations.AddField(
            model_name='korisnik',
            name='uloga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.uloga'),
        ),
    ]
