# Generated by Django 4.2.2 on 2023-06-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_korisnik_last_login_remove_korisnik_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uloga',
            name='ime',
            field=models.CharField(max_length=13),
        ),
    ]
