# Generated by Django 4.2.2 on 2023-06-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_predmet_nositelj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmet',
            name='ime',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='predmet',
            name='kod',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
