# Generated by Django 4.2.2 on 2023-06-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_predmet_ime_alter_predmet_kod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upis',
            name='status',
            field=models.CharField(choices=[('upisan', 'Upisan'), ('neupisan', 'Neupisan'), ('polozen', 'Položen')], max_length=10),
        ),
    ]
