# Generated by Django 4.2.2 on 2023-06-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_upis_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upis',
            name='status',
            field=models.CharField(choices=[('upisan', 'Upisan'), ('neupisan', 'Neupisan'), ('polozen', 'Položen'), ('dobio_potpis', 'Dobio Potpis'), ('izgubio_potpis', 'Izgubio Potpis')], default='upisan', max_length=14),
        ),
    ]
